name: novax_app
description: NOVAX Premium News Player
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.8.1
  flick_video_player: ^0.7.0
  http: ^1.1.0

flutter:
  uses-material-design: true
